"""Structured Findings Contract v1; validation only, no analysis algorithms."""

from enum import StrEnum
from typing import Annotated, Self

from pydantic import BaseModel, ConfigDict, Field, StringConstraints, model_validator

AnalysisId = Annotated[str, Field(pattern=r"^AN-[0-9]{6,}$")]
AttemptId = Annotated[str, Field(pattern=r"^ATT-[0-9]{6,}$")]
FindingId = Annotated[str, Field(pattern=r"^F-[0-9]{3,}$")]
NormalizedValue = Annotated[float, Field(strict=True, ge=0, le=1, allow_inf_nan=False)]
Timestamp = Annotated[int, Field(strict=True, ge=0)]


class AnalysisStatus(StrEnum):
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    UNANALYZABLE = "UNANALYZABLE"


class SkillCategory(StrEnum):
    HANDSHAPE = "HANDSHAPE"
    ORIENTATION = "ORIENTATION"
    LOCATION = "LOCATION"
    MOVEMENT = "MOVEMENT"
    TIMING = "TIMING"
    SEQUENCE = "SEQUENCE"
    MOVEMENT_RANGE = "MOVEMENT_RANGE"
    BODY_POSITION = "BODY_POSITION"


class FindingStatus(StrEnum):
    STRONG = "STRONG"
    ACCEPTABLE = "ACCEPTABLE"
    NEEDS_IMPROVEMENT = "NEEDS_IMPROVEMENT"
    WARNING = "WARNING"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class BodyRegion(StrEnum):
    LEFT_HAND = "LEFT_HAND"
    RIGHT_HAND = "RIGHT_HAND"
    BOTH_HANDS = "BOTH_HANDS"
    LEFT_ARM = "LEFT_ARM"
    RIGHT_ARM = "RIGHT_ARM"
    HEAD = "HEAD"
    UPPER_BODY = "UPPER_BODY"


class ContractModel(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)


class Evidence(ContractModel):
    """Metric semantics are defined by the future comparison engine."""

    expected_value: str
    observed_value: str
    deviation: float = Field(strict=True, allow_inf_nan=False)


class StructuredFinding(ContractModel):
    finding_id: FindingId
    skill: SkillCategory
    status: FindingStatus
    severity: int = Field(strict=True, ge=0, le=3, description="0 informational, 1 minor, 2 moderate, 3 major")
    confidence: NormalizedValue
    body_region: BodyRegion
    start_time_ms: Timestamp
    end_time_ms: Timestamp
    evidence: Evidence | None = Field(
        default=None, description="Required unless status is INSUFFICIENT_EVIDENCE."
    )

    @model_validator(mode="after")
    def validate_finding(self) -> Self:
        if self.end_time_ms < self.start_time_ms:
            raise ValueError("end_time_ms must be >= start_time_ms")
        if self.status != FindingStatus.INSUFFICIENT_EVIDENCE and self.evidence is None:
            raise ValueError("Evidence is required for performance judgment findings")
        return self


class StructuredAnalysisResult(ContractModel):
    """Completed, failed, or abstained result, never generated by these models.

    COMPLETED requires score and confidence. UNANALYZABLE requires confidence,
    forbids score, and permits only insufficient-evidence findings. FAILED
    forbids score and findings; confidence is optional.
    """

    analysis_id: AnalysisId
    attempt_id: AttemptId
    model_version: Annotated[str, StringConstraints(strip_whitespace=True, min_length=1)]
    status: AnalysisStatus
    overall_score: NormalizedValue | None = Field(
        default=None, description="Internal calibrated similarity; required for COMPLETED, otherwise null. Not a grade."
    )
    overall_confidence: NormalizedValue | None = Field(
        default=None, description="Required for COMPLETED and UNANALYZABLE; optional for FAILED."
    )
    findings: tuple[StructuredFinding, ...] = Field(
        description="May be empty. FAILED requires empty; UNANALYZABLE permits only INSUFFICIENT_EVIDENCE."
    )

    @model_validator(mode="after")
    def validate_terminal_state(self) -> Self:
        if self.status == AnalysisStatus.COMPLETED:
            if self.overall_score is None or self.overall_confidence is None:
                raise ValueError("COMPLETED requires overall_score and overall_confidence")
        else:
            if self.overall_score is not None:
                raise ValueError("FAILED and UNANALYZABLE must not include overall_score")
            if self.status == AnalysisStatus.UNANALYZABLE:
                if self.overall_confidence is None:
                    raise ValueError("UNANALYZABLE requires overall_confidence")
                if any(f.status != FindingStatus.INSUFFICIENT_EVIDENCE for f in self.findings):
                    raise ValueError("UNANALYZABLE permits only INSUFFICIENT_EVIDENCE findings")
            elif self.findings:
                raise ValueError("FAILED requires empty findings")
        return self
